########################################################################################################################
# Configuration for the Documentation Request issue template available for all Root & Blade GitHub repositories.
#
# @link https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository # editorconfig-checker-disable-line
#
---
name: Documentation Request
description: |
  Request updates or additions to documentation within the project.

title: "Documentation Request: "

labels:
  - "Request: Documentation"
  - "Priority: 03-Normal"
  - "Status: 00-Pending"

body:
  #
  # New or Updated
  #
  - type: dropdown
    id: update_or_novel
    attributes:
      label: Is this new documentation?
      description: |
        Is this an update to an existing documentation, or something novel to the application or service?
      options:
        - New Documentation
        - Update to Existing Documentation
    validations:
      required: true

  #
  # Product Name
  #
  - type: dropdown
    id: product
    attributes:
      label: What product(s) does this impact?
      description: |
        Which Root & Blade product(s) does this issue impact?
      options:
        - rootandblade.co
        - betterlawn.app (Website)
        - BetterLawn (Mobile App)
        - Other (Describe in "Other Details")
      multiple: true
    validations:
      required: true

  #
  # Summary
  #
  - type: textarea
    id: summary
    attributes:
      label: Documentation Summary
      description: |
        Please describe, in detail, what documentation needs to be added or updated in the platform.
    validations:
      required: true

  #
  # Motivation
  #
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Why should this documentation be prioritized? Who is impacted and how?
      placeholder: |
        The more viable and desirable documentation is, the higher it will land on our priority list.
    validations:
      required: true

  #
  # Other Details
  #
  - type: textarea
    id: other_details
    attributes:
      label: Other Details
      description: |
        If there is anything else helpful that you think we should know, please include it here.
    validations:
      required: false

  #
  # Terms and Conditions
  #
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this Issue, you agree to follow our Code of Conduct (available in `CODE_OF_CONDUCT.md`)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
